// Handlers
import { handleSync, handleSyncAll, handleSyncNick, handleRefreshCache, handleWarn, handleUnwarn, handleWarns, handleMute, handleUnmute, handleBan, handleInacAll, handleInacList, handleConcluida, handleCadastrarMissao, handleEntrou, handleEscrever } from './admin.js';
import { handleHelp, handleStats, handleClan, handleActive, handleRegras, handleMissoes, handleMotd, handleBirthday, handleGames } from './public.js';
import { handleDaily, handleBalance, handleHistorico, handleLeaderboard, handleShop, handleBuy, handleAddProvider, handleRemoveProvider, handleConquistas, handleStreak, handleAddCoins } from './tggCoinsCommands.js';

// Command Aliases
export const COMMAND_ALIASES = {
  'help': 'help',
  'ajuda': 'help',
  'comandos': 'help',
  'regras': 'regras',
  'rules': 'regras',
  'reguas': 'regras',
  'legolas': 'regras',
  'stats': 'stats',
  'status': 'stats',
  'estatisticas': 'stats',
  'clan': 'clan',
  'clã': 'clan',
  'missoes': 'missoes',
  'missões': 'missoes',
  'missao': 'missoes',
  'missão': 'missoes',
  'missions': 'missoes',
  'active': 'active',
  'sync': 'sync',
  'sync-guild': 'sync',
  'sync-roles': 'sync',
  'sync-elo': 'sync',
  'sync-all': 'sync-all',
  'sync-nick': 'sync-nick',
  'sync-nicknames': 'sync-nick',
  'refresh-cache': 'refresh-cache',
  'warn': 'warn',
  'unwarn': 'unwarn',
  'warns': 'warns',
  'warnings': 'warns',
  'mute': 'mute',
  'unmute': 'unmute',
  'ban': 'ban',
  'inac-all': 'inac-all',
  'inac-list': 'inac-list',
  'concluida': 'concluida',
  'concluída': 'concluida',
  'concluido': 'concluida',
  'concluído': 'concluida',
  'comcluido': 'concluida', // Becca
  'cadastrarmissao': 'cadastrarmissao',
  'cadastrarmissão': 'cadastrarmissao',
  'entrou': 'entrou',
  'daily': 'daily',
  'diario': 'daily',
  'diaria': 'daily',
  'diária': 'daily',
  'diário': 'daily',
  'deili': 'daily', // CrZ
  'balance': 'balance',
  'bal': 'balance',
  'coins': 'balance',
  'moedas': 'balance',
  'saldo  ': 'balance',
  'historico': 'historico',
  'histórico': 'historico',
  'history': 'historico',
  'hist': 'historico',
  'leaderboard': 'leaderboard',
  'lb': 'leaderboard',
  'shop': 'shop',
  'loja': 'shop',
  'buy': 'buy',
  'comprar': 'buy',
  'conquistas': 'conquistas',
  'conquista': 'conquistas',
  'achievements': 'conquistas',
  'achievement': 'conquistas',
  'streak': 'streak',
  'sequencia': 'streak',
  'sequência': 'streak',
  'motd': 'motd',
  'birthday': 'birthday',
  'aniversario': 'birthday',
  'aniversário': 'birthday',
  'games': 'games',
  'jogos': 'games',
  'addprovider': 'addprovider',
  'removeprovider': 'removeprovider',
  'addcoins': 'addcoins',
  'escrever': 'escrever',
  'write': 'escrever'
};

// Lista de comandos
export const commands = {
  // Públicos
  help: handleHelp,
  regras: handleRegras,
  motd: handleMotd,
  stats: handleStats,
  clan: handleClan,
  missoes: handleMissoes,
  active: handleActive,
  birthday: handleBirthday,
  games: handleGames,

  // Admin
  sync: handleSync,
  'sync-all': handleSyncAll,
  'sync-nick': handleSyncNick,
  'refresh-cache': handleRefreshCache,
  warn: handleWarn,
  unwarn: handleUnwarn,
  warns: handleWarns,
  mute: handleMute,
  unmute: handleUnmute,
  ban: handleBan,
  'inac-all': handleInacAll,
  'inac-list': handleInacList,
  concluida: handleConcluida,
  cadastrarmissao: handleCadastrarMissao,
  entrou: handleEntrou,
  escrever: handleEscrever,

  // TGG-Coins
  daily: handleDaily,
  balance: handleBalance,
  historico: handleHistorico,
  leaderboard: handleLeaderboard,
  shop: handleShop,
  buy: handleBuy,
  conquistas: handleConquistas,
  streak: handleStreak,
  addprovider: handleAddProvider,
  removeprovider: handleRemoveProvider,
  addcoins: handleAddCoins
};
