// Handlers
import { handleSync, handleSyncAll, handleSyncNick, handleRefreshCache, handleWarn, handleUnwarn, handleWarns, handleEditWarn, handleMute, handleUnmute, handleBan, handleBam, handleInacAll, handleInacList, handleConcluida, handleCadastrarMissao, handleEntrou, handleEscrever, handleOrganizeTickets, handleAbrirTickets, handleFecharTickets, handleWam, handleJustificativas, handleResumo } from './admin.js';
import { handleHelp, handleStats, handleGuild, handleActive, handleRegras, handleMissoes, handleMotd, handleBirthday, handleGames, handleCorrigirID, handleRedes, handleDuel, handleCrz } from './public.js';
import { handleDaily, handleBalance, handleHistorico, handleLeaderboard, handleShop, handleBuy, handleAddProvider, handleRemoveProvider, handleConquistas, handleStreak, handleAddCoins, handleAddAccount, handleQuiz, handleInventory } from './tggCoinsCommands.js';

// Command Aliases
export const COMMAND_ALIASES = {
  'help': 'help',
  'ajuda': 'help',
  'comandos': 'help',
  'regras': 'regras',
  'rules': 'regras',
  'reguas': 'regras',
  'legolas': 'regras',
  'stats': 'stats',
  'status': 'stats',
  'estatisticas': 'stats',
  'guilda': 'guild',
  'guild': 'guild',
  'clan': 'guild',
  'clã': 'guild',
  'missoes': 'missoes',
  'missões': 'missoes',
  'missao': 'missoes',
  'missão': 'missoes',
  'missions': 'missoes',
  'active': 'active',
  'sync': 'sync',
  'sync-guild': 'sync',
  'sync-roles': 'sync',
  'sync-elo': 'sync',
  'sync-all': 'sync-all',
  'sync-nick': 'sync-nick',
  'sync-nicknames': 'sync-nick',
  'refresh-cache': 'refresh-cache',
  'warn': 'warn',
  'unwarn': 'unwarn',
  'warns': 'warns',
  'warnings': 'warns',
  'edit-warn': 'edit-warn',
  'editwarn': 'edit-warn',
  'mute': 'mute',
  'unmute': 'unmute',
  'ban': 'ban',
  'banir': 'ban',
  'bam': 'bam',
  'inac-all': 'inac-all',
  'inac-list': 'inac-list',
  'concluida': 'concluida',
  'concluída': 'concluida',
  'concluido': 'concluida',
  'concluído': 'concluida',
  'comcluido': 'concluida', // Becca
  'cadastrarmissao': 'cadastrarmissao',
  'cadastrarmissão': 'cadastrarmissao',
  'entrou': 'entrou',
  'daily': 'daily',
  'daili': 'daily',
  'dayly': 'daily',
  'dayli': 'daily',
  'diario': 'daily',
  'diaria': 'daily',
  'diária': 'daily',
  'diário': 'daily',
  'deili': 'daily', // CrZ
  'deily': 'daily',
  'deyly': 'daily',
  'deyli': 'daily',
  'deiucu': 'daily', // Gameru
  'deiocu': 'daily',
  'dailhe': 'daily', // Violet
  'daocu': 'daily', // Picturii
  'pizzolho': 'daily', // ADM_Bart
  'dekko': 'daily', // Dekkosun
  'miguel-kyna-lopes-yüz-da-silva': 'daily', // Mig
  'a-sol-falou-que-me-amava-e-eu-tenho-certeza-de-que-foi-tudo-coisa-da-minha-cabeça...': 'daily', // Kay
  'balance': 'balance',
  'bal': 'balance',
  'baal': 'balance',
  'coins': 'balance',
  'moedas': 'balance',
  'saldo  ': 'balance',
  'historico': 'historico',
  'histórico': 'historico',
  'history': 'historico',
  'hist': 'historico',
  'compra': 'historico',
  'compras': 'historico',
  'leaderboard': 'leaderboard',
  'lb': 'leaderboard',
  'shop': 'shop',
  'loja': 'shop',
  'store': 'shop',
  'buy': 'buy',
  'comprar': 'buy',
  'inventory': 'inventory',
  'inventario': 'inventory',
  'inventário': 'inventory',
  'inv': 'inventory',
  'cores': 'inventory',
  'cor': 'inventory',
  'conquistas': 'conquistas',
  'conquista': 'conquistas',
  'achievements': 'conquistas',
  'achievement': 'conquistas',
  'streak': 'streak',
  'sequencia': 'streak',
  'sequência': 'streak',
  'motd': 'motd',
  'modt': 'motd',
  'mdt': 'motd',
  'mtd': 'motd',
  'birthday': 'birthday',
  'aniversario': 'birthday',
  'aniversário': 'birthday',
  'games': 'games',
  'gaymes': 'games',
  'jogos': 'games',
  'partidas': 'games',
  'addprovider': 'addprovider',
  'removeprovider': 'removeprovider',
  'addcoins': 'addcoins',
  'escrever': 'escrever',
  'write': 'escrever',
  'organizarTickets': 'organize-tickets',
  'arrumarTickets': 'organize-tickets',
  'organizar-tickets': 'organize-tickets',
  'arrumar-tickets': 'organize-tickets',
  'corrigirid': 'corrigir-id',
  'corrigir-id': 'corrigir-id',
  'addaccount': 'add-account',
  'add-account': 'add-account',
  'vincular-conta': 'add-account',
  'vincularconta': 'add-account',
  'adicionarconta': 'add-account',
  'adicionar-conta': 'add-account',
  'add-acc': 'add-account',
  'addacc': 'add-account',
  'quiz': 'quiz',
  'quis': 'quiz',
  'cuiz': 'quiz',
  'abrir-tickets': 'abrir-tickets',
  'fechar-tickets': 'fechar-tickets',
  'wam': 'wam',
  'warm': 'wam',
  'vvarn': 'wam',
  'vvam': 'wam',
  'redes': 'redes',
  'rede': 'redes',
  'redes-sociais': 'redes',
  'redessociais': 'redes',
  'redesociais': 'redes',
  'socials': 'redes',
  'sociais': 'redes',
  'discord': 'redes',
  'youtube': 'redes',
  'yt': 'redes',
  'tiktok': 'redes',
  'twitch': 'redes',
  'ttv': 'redes',
  'spotify': 'redes',
  'site': 'redes',
  'exitlag': 'redes',
  'duel': 'duel',
  'duelo': 'duel',
  'batalha': 'duel',
  'battle': 'duel',
  'justificativas': 'justificativas',
  'justificativa': 'justificativas',
  'mentiras': 'justificativas',
  'mentira': 'justificativas',
  'desculpas': 'justificativas',
  'desculpa': 'justificativas',
  'resumo': 'resumo',
  'resumao': 'resumo',
  'resumão': 'resumo',
  'crz': 'crz',
};

// Lista de comandos
export const commands = {
  // Públicos
  help: handleHelp,
  regras: handleRegras,
  motd: handleMotd,
  stats: handleStats,
  guild: handleGuild,
  missoes: handleMissoes,
  active: handleActive,
  birthday: handleBirthday,
  games: handleGames,
  'corrigir-id': handleCorrigirID,
  redes: handleRedes,
  duel: handleDuel,
  crz: handleCrz,

  // Admin
  sync: handleSync,
  'sync-all': handleSyncAll,
  'sync-nick': handleSyncNick,
  'refresh-cache': handleRefreshCache,
  warn: handleWarn,
  wam: handleWam,
  unwarn: handleUnwarn,
  warns: handleWarns,
  'edit-warn': handleEditWarn,
  mute: handleMute,
  unmute: handleUnmute,
  ban: handleBan,
  bam: handleBam,
  'inac-all': handleInacAll,
  'inac-list': handleInacList,
  concluida: handleConcluida,
  cadastrarmissao: handleCadastrarMissao,
  entrou: handleEntrou,
  escrever: handleEscrever,
  'organize-tickets': handleOrganizeTickets,
  'abrir-tickets': handleAbrirTickets,
  'fechar-tickets': handleFecharTickets,
  justificativas: handleJustificativas,
  resumo: handleResumo,

  // TGG-Coins
  daily: handleDaily,
  balance: handleBalance,
  historico: handleHistorico,
  leaderboard: handleLeaderboard,
  shop: handleShop,
  buy: handleBuy,
  conquistas: handleConquistas,
  streak: handleStreak,
  quiz: handleQuiz,
  addprovider: handleAddProvider,
  removeprovider: handleRemoveProvider,
  addcoins: handleAddCoins,
  'add-account': handleAddAccount,
  inventory: handleInventory
};
